version: "0.2"
words:
  - actix
  - addrs
  - ALPN
  - arrayvec
  - bitflags
  - clippy
  - deque
  - itertools
  - itoa
  - mptcp
  - MSRV
  - nonblocking
  - oneshot
  - pemfile
  - rcgen
  - Rustls
  - rustup
  - smallvec
  - spki
  - uring
  - webpki
